/**
 * Seed script for initial personality questions
 *
 * Run this script with:
 * npx ts-node src/personality/seed-questions.ts
 */

import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { PersonalityService } from './personality.service';
import { Logger } from '@nestjs/common';

const logger = new Logger('SeedQuestions');

const initialQuestions = [
  // ============ SECTION: Demographics / Basisdaten ============
  {
    key: 'country',
    question: 'In welchem Land lebst du überwiegend?',
    type: 'free_text',
    dimension: 'region',
    section: 'demographics',
    sectionTitle: 'Basisdaten',
    sectionDescription: 'Rahmenbedingungen wie Region, Lebenssituation und Beruf.',
    active: true,
    order: 100,
  },
  {
    key: 'age_range',
    question: 'In welcher Altersgruppe befindest du dich?',
    type: 'single_choice',
    dimension: 'alter',
    section: 'demographics',
    sectionTitle: 'Basisdaten',
    sectionDescription: 'Rahmenbedingungen wie Region, Lebenssituation und Beruf.',
    structuredOptions: [
      { value: 'u20', label: 'Unter 20' },
      { value: '20_29', label: '20–29' },
      { value: '30_39', label: '30–39' },
      { value: '40_49', label: '40–49' },
      { value: '50_59', label: '50–59' },
      { value: '60_plus', label: '60 oder älter' },
      { value: 'no_say', label: 'Möchte ich nicht sagen' },
    ],
    active: true,
    order: 101,
  },
  {
    key: 'family_status',
    question: 'Wie ist dein Familienstand?',
    type: 'single_choice',
    dimension: 'familienstand',
    section: 'demographics',
    sectionTitle: 'Basisdaten',
    sectionDescription: 'Rahmenbedingungen wie Region, Lebenssituation und Beruf.',
    structuredOptions: [
      { value: 'single', label: 'Single' },
      { value: 'relationship', label: 'In Beziehung, nicht verheiratet' },
      { value: 'married_no_children', label: 'Verheiratet ohne Kinder' },
      { value: 'married_children', label: 'Verheiratet mit Kindern' },
      { value: 'single_parent', label: 'Alleinerziehend' },
      { value: 'other', label: 'Sonstiges' },
      { value: 'no_say', label: 'Möchte ich nicht sagen' },
    ],
    active: true,
    order: 102,
  },
  {
    key: 'profession_field',
    question: 'In welchem beruflichen Bereich arbeitest du überwiegend?',
    type: 'single_choice_other',
    dimension: 'berufsfeld',
    section: 'demographics',
    sectionTitle: 'Basisdaten',
    sectionDescription: 'Rahmenbedingungen wie Region, Lebenssituation und Beruf.',
    structuredOptions: [
      { value: 'it_tech', label: 'IT / Tech' },
      { value: 'finance', label: 'Finanzen / Banking / Trading' },
      { value: 'creative', label: 'Kreativwirtschaft / Medien / Kunst' },
      { value: 'management', label: 'Management / Beratung' },
      { value: 'health', label: 'Gesundheit / Soziales' },
      { value: 'education', label: 'Bildung / Wissenschaft' },
      { value: 'self_employed', label: 'Selbstständig / Unternehmer:in' },
      { value: 'other', label: 'Sonstiges' },
    ],
    active: true,
    order: 103,
  },
  {
    key: 'work_seniority',
    question: 'Wie ist dein Erfahrungslevel im Berufsleben?',
    type: 'single_choice',
    dimension: 'beruf_erfahrung',
    section: 'demographics',
    sectionTitle: 'Basisdaten',
    sectionDescription: 'Rahmenbedingungen wie Region, Lebenssituation und Beruf.',
    structuredOptions: [
      { value: 'student', label: 'Schüler:in / Student:in' },
      { value: 'entry', label: 'Berufseinsteiger:in' },
      { value: 'professional', label: 'Berufserfahren (3–10 Jahre)' },
      { value: 'senior', label: 'Senior (10+ Jahre)' },
      { value: 'executive', label: 'Führungskraft / C-Level' },
      { value: 'other', label: 'Sonstiges' },
    ],
    active: true,
    order: 104,
  },
  {
    key: 'availability_times',
    question: 'Wann bist du typischerweise für Poker / Projekte verfügbar?',
    type: 'multi_choice',
    dimension: 'verfuegbarkeit_zeit',
    section: 'demographics',
    sectionTitle: 'Basisdaten',
    sectionDescription: 'Rahmenbedingungen wie Region, Lebenssituation und Beruf.',
    structuredOptions: [
      { value: 'weekday_morning', label: 'Wochentags morgens' },
      { value: 'weekday_afternoon', label: 'Wochentags nachmittags' },
      { value: 'weekday_evening', label: 'Wochentags abends' },
      { value: 'weekend', label: 'Wochenenden' },
      { value: 'variable', label: 'Sehr variabel' },
    ],
    active: true,
    order: 105,
  },

  // ============ SECTION: Big Five ============
  {
    key: 'bf_offenheit_1',
    question: 'Ich probiere gerne neue Ideen, Strategien oder ungewöhnliche Lösungen aus.',
    type: 'scale_1_5',
    dimension: 'big_five.offenheit',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 200,
  },
  {
    key: 'bf_offenheit_2',
    question: 'Kreative oder komplexe Probleme ziehen mich eher an als Routineaufgaben.',
    type: 'scale_1_5',
    dimension: 'big_five.offenheit',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 201,
  },
  {
    key: 'bf_gewissenhaft_1',
    question: 'Ich arbeite strukturiert, plane voraus und halte mich an meine Pläne.',
    type: 'scale_1_5',
    dimension: 'big_five.gewissenhaftigkeit',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 202,
  },
  {
    key: 'bf_gewissenhaft_2',
    question: 'Ich achte stark auf Details und vermeide unnötige Risiken.',
    type: 'scale_1_5',
    dimension: 'big_five.gewissenhaftigkeit',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 203,
  },
  {
    key: 'bf_extraversion_1',
    question: 'Ich bekomme Energie durch Austausch mit anderen Menschen.',
    type: 'scale_1_5',
    dimension: 'big_five.extraversion',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 204,
  },
  {
    key: 'bf_extraversion_2',
    question: 'Ich fühle mich wohl damit, in Gruppen das Wort zu ergreifen oder zu führen.',
    type: 'scale_1_5',
    dimension: 'big_five.extraversion',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 205,
  },
  {
    key: 'bf_vertraeglichkeit_1',
    question: 'Mir ist wichtig, dass Zusammenarbeit harmonisch und respektvoll abläuft.',
    type: 'scale_1_5',
    dimension: 'big_five.vertraeglichkeit',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 206,
  },
  {
    key: 'bf_vertraeglichkeit_2',
    question: 'Ich bin eher kompromissbereit als auf Konfrontation aus.',
    type: 'scale_1_5',
    dimension: 'big_five.vertraeglichkeit',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 207,
  },
  {
    key: 'bf_neurotizismus_1',
    question: 'Starke Verluste, Konflikte oder Fehler beschäftigen mich lange emotional.',
    type: 'scale_1_5',
    dimension: 'big_five.neurotizismus',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 208,
  },
  {
    key: 'bf_neurotizismus_2',
    question: 'Unter Druck oder Zeitstress werde ich schnell unruhig.',
    type: 'scale_1_5',
    dimension: 'big_five.neurotizismus',
    section: 'big_five',
    sectionTitle: 'Persönlichkeit (Big Five)',
    sectionDescription: 'Bitte gib an, wie sehr du den Aussagen zustimmst. 1 = stimme überhaupt nicht zu, 5 = stimme voll zu.',
    scaleType: 'likert_1_5',
    scaleLabels: {
      '1': 'stimme überhaupt nicht zu',
      '2': 'stimme eher nicht zu',
      '3': 'teils/teils',
      '4': 'stimme eher zu',
      '5': 'stimme voll zu',
    },
    active: true,
    order: 209,
  },

  // ============ SECTION: Decision Style & Risk ============
  {
    key: 'risk_tendency',
    question: 'Wie hoch ist deine typische Risikobereitschaft in wichtigen Entscheidungen?',
    type: 'single_choice',
    dimension: 'risiko',
    section: 'decision_style',
    sectionTitle: 'Entscheidungsstil & Risiko',
    sectionDescription: 'Wie triffst du Entscheidungen in unsicheren Situationen (Poker & Business)?',
    structuredOptions: [
      { value: 'risk_averse', label: 'Eher risikoarm – ich sichere lieber ab als zu pushen.' },
      { value: 'moderate', label: 'Ausgewogen – Risiko, wenn es gut begründet ist.' },
      { value: 'risk_seeking', label: 'Eher risikofreudig – ich gehe auch hohe Wetten ein, wenn die Chance spannend ist.' },
    ],
    active: true,
    order: 300,
  },
  {
    key: 'decision_style_primary',
    question: 'Welcher Entscheidungsstil beschreibt dich am besten?',
    type: 'single_choice',
    dimension: 'entscheidungsstil_haupt',
    section: 'decision_style',
    sectionTitle: 'Entscheidungsstil & Risiko',
    sectionDescription: 'Wie triffst du Entscheidungen in unsicheren Situationen (Poker & Business)?',
    structuredOptions: [
      { value: 'rational', label: 'Rational – ich analysiere Daten, Fakten und Wahrscheinlichkeiten.' },
      { value: 'intuitive', label: 'Intuitiv – ich verlasse mich stark auf Gefühl und Erfahrung.' },
      { value: 'dependent', label: 'Abhängig – ich hole gerne Meinungen anderer ein, bevor ich entscheide.' },
      { value: 'spontaneous', label: 'Spontan – ich entscheide schnell und reagiere im Moment.' },
      { value: 'avoidant', label: 'Vermeidend – ich schiebe Entscheidungen eher auf, wenn es möglich ist.' },
    ],
    active: true,
    order: 301,
  },
  {
    key: 'decision_speed',
    question: 'Wie schnell triffst du typischerweise Entscheidungen bei Unsicherheit?',
    type: 'single_choice',
    dimension: 'entscheidungs_geschwindigkeit',
    section: 'decision_style',
    sectionTitle: 'Entscheidungsstil & Risiko',
    sectionDescription: 'Wie triffst du Entscheidungen in unsicheren Situationen (Poker & Business)?',
    structuredOptions: [
      { value: 'very_fast', label: 'Sehr schnell – ich entscheide fast sofort.' },
      { value: 'fast', label: 'Relativ schnell – ein kurzer Check reicht mir.' },
      { value: 'balanced', label: 'Ausgewogen – ich nehme mir etwas Zeit, aber nicht zu lange.' },
      { value: 'slow', label: 'Eher langsam – ich möchte möglichst viele Infos sehen.' },
    ],
    active: true,
    order: 302,
  },
  {
    key: 'conflict_style',
    question: 'Wie gehst du mit Konflikten und starken Meinungsverschiedenheiten um?',
    type: 'single_choice',
    dimension: 'konfliktstil',
    section: 'decision_style',
    sectionTitle: 'Entscheidungsstil & Risiko',
    sectionDescription: 'Wie triffst du Entscheidungen in unsicheren Situationen (Poker & Business)?',
    structuredOptions: [
      { value: 'collaborating', label: 'Kollaborativ – ich suche aktiv nach Lösungen, die für alle gut sind.' },
      { value: 'compromising', label: 'Kompromissorientiert – jede Seite gibt etwas nach.' },
      { value: 'avoiding', label: 'Vermeidend – ich gehe Konflikten lieber aus dem Weg.' },
      { value: 'competing', label: 'Durchsetzend – ich vertrete meine Position stark und direkt.' },
      { value: 'accommodating', label: 'Anpassend – ich stelle Harmonie über meine eigene Position.' },
    ],
    active: true,
    order: 303,
  },
  {
    key: 'motivation_drivers',
    question: 'Was treibt dich bei Projekten oder beim Poker am meisten an?',
    type: 'multi_choice',
    dimension: 'motivation',
    section: 'decision_style',
    sectionTitle: 'Entscheidungsstil & Risiko',
    sectionDescription: 'Wie triffst du Entscheidungen in unsicheren Situationen (Poker & Business)?',
    structuredOptions: [
      { value: 'autonomy', label: 'Autonomie – Freiheit, selbst zu entscheiden und zu gestalten.' },
      { value: 'competence', label: 'Kompetenz – besser werden, Probleme meistern, Skills ausbauen.' },
      { value: 'relatedness', label: 'Verbundenheit – Austausch mit anderen, Teil eines Teams sein.' },
      { value: 'status_recognition', label: 'Status / Anerkennung – Respekt, Ranglisten, Erfolge sichtbar machen.' },
      { value: 'financial', label: 'Finanzieller Erfolg – Geld / ROI stehen im Vordergrund.' },
    ],
    active: true,
    order: 304,
  },

  // ============ SECTION: Poker Profile ============
  {
    key: 'poker_experience',
    question: 'Wie schätzt du dein Poker-Erfahrungslevel ein?',
    type: 'single_choice',
    dimension: 'poker_erfahrung',
    section: 'poker_profile',
    sectionTitle: 'Poker-Profil',
    sectionDescription: 'Dein typischer Stil und deine Ziele im Poker.',
    structuredOptions: [
      { value: 'beginner', label: 'Einsteiger: weniger als 1 Jahr / wenig Volumen.' },
      { value: 'intermediate', label: 'Fortgeschritten: solide Basis, regelmäßiges Spiel.' },
      { value: 'reg', label: 'Reg: ich spiele strukturiert, mit Tracking / Theoriearbeit.' },
      { value: 'pro', label: 'Profi / Semi-Profi: Poker ist einer meiner Haupt-Einkommensquellen.' },
    ],
    active: true,
    order: 400,
  },
  {
    key: 'poker_formats',
    question: 'Welche Formate spielst du hauptsächlich?',
    type: 'multi_choice',
    dimension: 'poker_formate',
    section: 'poker_profile',
    sectionTitle: 'Poker-Profil',
    sectionDescription: 'Dein typischer Stil und deine Ziele im Poker.',
    structuredOptions: [
      { value: 'cashgame', label: 'Cashgame' },
      { value: 'mtt', label: 'MTT (Multi-Table Turniere)' },
      { value: 'sng', label: 'Sit & Go' },
      { value: 'plo', label: 'PLO (Pot Limit Omaha)' },
      { value: 'mixed', label: 'Mixed Games / andere Varianten' },
      { value: 'live', label: 'Live Poker (Casino / Homegames)' },
      { value: 'online', label: 'Online Poker' },
    ],
    active: true,
    order: 401,
  },
  {
    key: 'poker_goal',
    question: 'Was ist dein Hauptziel beim Poker?',
    type: 'single_choice',
    dimension: 'poker_ziel',
    section: 'poker_profile',
    sectionTitle: 'Poker-Profil',
    sectionDescription: 'Dein typischer Stil und deine Ziele im Poker.',
    structuredOptions: [
      { value: 'fun', label: 'Spaß / Entertainment' },
      { value: 'learning', label: 'Lernen / besser werden' },
      { value: 'side_income', label: 'Solides Nebeneinkommen' },
      { value: 'main_income', label: 'Haupteinkommen / professionelle Karriere' },
    ],
    active: true,
    order: 402,
  },
  {
    key: 'poker_style_self',
    question: 'Wie würdest du deinen Spielstil grob einordnen?',
    type: 'single_choice',
    dimension: 'poker_stil_selbstbild',
    section: 'poker_profile',
    sectionTitle: 'Poker-Profil',
    sectionDescription: 'Dein typischer Stil und deine Ziele im Poker.',
    structuredOptions: [
      { value: 'nit', label: 'Sehr tight und eher vorsichtig (Nit).' },
      { value: 'tag', label: 'Tight-aggressiv: selektiv, aber druckvoll gespielt (TAG).' },
      { value: 'lag', label: 'Loose-aggressiv: viele Spots, viel Druck (LAG).' },
      { value: 'loose_passive', label: 'Loose-passiv: viele Calls, eher selten Raises.' },
      { value: 'balanced', label: 'Ausgewogen / schwer einzuordnen.' },
    ],
    active: true,
    order: 403,
  },
  {
    key: 'poker_tilt_behavior',
    question: 'Wie reagierst du typischerweise auf Bad Beats oder Downswings?',
    type: 'single_choice',
    dimension: 'poker_tilt',
    section: 'poker_profile',
    sectionTitle: 'Poker-Profil',
    sectionDescription: 'Dein typischer Stil und deine Ziele im Poker.',
    structuredOptions: [
      { value: 'tilt_low', label: 'Ich bleibe meist ruhig und halte mich strikt an meinen Gameplan.' },
      { value: 'tilt_medium', label: 'Ich merke, dass ich looser werde, fange mich aber nach einiger Zeit.' },
      { value: 'tilt_high', label: 'Ich kippe schnell in Tilt und spiele deutlich schlechter / aggressiver.' },
      { value: 'tilt_escape', label: 'Ich breche relativ früh ab, sobald ich merke, dass ich nicht mehr gut spiele.' },
    ],
    active: true,
    order: 404,
  },
  {
    key: 'poker_learning_style',
    question: 'Wie lernst du am liebsten Poker?',
    type: 'multi_choice',
    dimension: 'poker_lernstil',
    section: 'poker_profile',
    sectionTitle: 'Poker-Profil',
    sectionDescription: 'Dein typischer Stil und deine Ziele im Poker.',
    structuredOptions: [
      { value: 'theory_videos', label: 'Theorie-Videos / Streams schauen.' },
      { value: 'solvers', label: 'Solver / Tools / Datenanalyse.' },
      { value: 'coaching', label: '1:1 Coaching oder Gruppen-Coaching.' },
      { value: 'hand_reviews', label: 'Handhistories gemeinsam durchgehen.' },
      { value: 'solo_play', label: 'Einfach spielen und aus Erfahrung lernen.' },
    ],
    active: true,
    order: 405,
  },

  // ============ SECTION: Business Profile ============
  {
    key: 'business_role_type',
    question: 'Welche Rolle trifft dich in Projekten am ehesten?',
    type: 'single_choice',
    dimension: 'business_rolle',
    section: 'business_profile',
    sectionTitle: 'Business- / Projekt-Profil',
    sectionDescription: 'Wie arbeitest du in Projekten und Teams am liebsten?',
    structuredOptions: [
      { value: 'visionary', label: 'Visionär: neue Ideen, große Linien, Richtung vorgeben.' },
      { value: 'analyst', label: 'Analyst: Daten, Struktur, Modelle, Risikoabwägung.' },
      { value: 'implementer', label: 'Umsetzer: Dinge ins Laufen bringen, To-Dos abhaken.' },
      { value: 'coordinator', label: 'Koordinator: Menschen zusammenbringen, Abstimmung, Kommunikation.' },
      { value: 'specialist', label: 'Spezialist: tiefe Expertise in einem spezifischen Bereich.' },
    ],
    active: true,
    order: 500,
  },
  {
    key: 'work_style',
    question: 'Welcher Arbeitsstil passt am besten zu dir?',
    type: 'single_choice',
    dimension: 'arbeitsstil',
    section: 'business_profile',
    sectionTitle: 'Business- / Projekt-Profil',
    sectionDescription: 'Wie arbeitest du in Projekten und Teams am liebsten?',
    structuredOptions: [
      { value: 'planner', label: 'Planer: ich brauche Struktur, Roadmaps und klare Schritte.' },
      { value: 'improviser', label: 'Improvisierer: ich reagiere gerne flexibel auf das, was kommt.' },
      { value: 'optimizer', label: 'Optimierer: ich verbessere laufende Prozesse und Systeme.' },
      { value: 'experimenter', label: 'Experimentierer: ich teste gerne viele neue Ansätze parallel.' },
    ],
    active: true,
    order: 501,
  },
  {
    key: 'communication_style',
    question: 'Wie kommunizierst du am liebsten in Projekten?',
    type: 'single_choice',
    dimension: 'kommunikationsstil',
    section: 'business_profile',
    sectionTitle: 'Business- / Projekt-Profil',
    sectionDescription: 'Wie arbeitest du in Projekten und Teams am liebsten?',
    structuredOptions: [
      { value: 'direct', label: 'Direkt und klar – lieber ehrlich als diplomatisch.' },
      { value: 'diplomatic', label: 'Diplomatisch – ich achte stark auf Formulierungen und Beziehungen.' },
      { value: 'detailed', label: 'Detailorientiert – ich erkläre Dinge gern ausführlich und präzise.' },
      { value: 'high_level', label: 'High-Level – ich fokussiere eher Vision, Ziele und Zusammenhänge.' },
    ],
    active: true,
    order: 502,
  },
  {
    key: 'decision_responsibility',
    question: 'Wie wohl fühlst du dich damit, finale Entscheidungen zu tragen?',
    type: 'single_choice',
    dimension: 'entscheidungsverantwortung',
    section: 'business_profile',
    sectionTitle: 'Business- / Projekt-Profil',
    sectionDescription: 'Wie arbeitest du in Projekten und Teams am liebsten?',
    structuredOptions: [
      { value: 'low', label: 'Ich übernehme ungern finale Verantwortung, arbeite lieber im Hintergrund.' },
      { value: 'medium', label: 'Ich teile Verantwortung gerne im Team.' },
      { value: 'high', label: 'Ich habe kein Problem damit, die finale Entscheidung zu treffen und zu vertreten.' },
    ],
    active: true,
    order: 503,
  },

  // ============ SECTION: Matching Preferences ============
  {
    key: 'match_skill_level',
    question: 'Mit welchem Skill-Level möchtest du bevorzugt gematcht werden?',
    type: 'single_choice',
    dimension: 'matching_skill',
    section: 'matching_preferences',
    sectionTitle: 'Matching-Präferenzen',
    sectionDescription: 'Wie sollen Poker-Partner:innen / Business-Partner:innen für dich sein?',
    structuredOptions: [
      { value: 'similar', label: 'Ähnliches Level wie ich.' },
      { value: 'stronger', label: 'Eher etwas stärker als ich (ich will lernen).' },
      { value: 'weaker', label: 'Eher etwas schwächer (ich möchte eher führen / coachen).' },
      { value: 'all', label: 'Alle – gerne durchmischte Gruppen.' },
    ],
    active: true,
    order: 600,
  },
  {
    key: 'match_risk_profile',
    question: 'Bevorzugst du eher ähnliche oder kontrastierende Risikoprofile in deinem Match?',
    type: 'single_choice',
    dimension: 'matching_risiko',
    section: 'matching_preferences',
    sectionTitle: 'Matching-Präferenzen',
    sectionDescription: 'Wie sollen Poker-Partner:innen / Business-Partner:innen für dich sein?',
    structuredOptions: [
      { value: 'similar', label: 'Ähnlich – wir sollten ähnlich riskant / sicher unterwegs sein.' },
      { value: 'complementary', label: 'Komplementär – ich mag Gegensätze, die neue Perspektiven bringen.' },
      { value: 'no_preference', label: 'Keine besondere Präferenz.' },
    ],
    active: true,
    order: 601,
  },
  {
    key: 'match_region_preference',
    question: 'Wie wichtig ist dir, dass dein Match aus deiner Region / Zeitzone kommt?',
    type: 'single_choice',
    dimension: 'matching_region',
    section: 'matching_preferences',
    sectionTitle: 'Matching-Präferenzen',
    sectionDescription: 'Wie sollen Poker-Partner:innen / Business-Partner:innen für dich sein?',
    structuredOptions: [
      { value: 'same_timezone', label: 'Gleich / ähnliche Zeitzone ist mir wichtig.' },
      { value: 'same_region', label: 'Gleiche Region / Kultur wäre gut, aber nicht Pflicht.' },
      { value: 'no_preference', label: 'Ist mir egal, solange die Chemie stimmt.' },
    ],
    active: true,
    order: 602,
  },
  {
    key: 'match_communication_preference',
    question: 'Welche Art von Kommunikationsstil wünschst du dir in deinem Match am meisten?',
    type: 'single_choice',
    dimension: 'matching_kommunikation',
    section: 'matching_preferences',
    sectionTitle: 'Matching-Präferenzen',
    sectionDescription: 'Wie sollen Poker-Partner:innen / Business-Partner:innen für dich sein?',
    structuredOptions: [
      { value: 'very_direct', label: 'Sehr direkt – keine Umwege, klare Ansagen.' },
      { value: 'kind_direct', label: 'Direkt, aber wertschätzend.' },
      { value: 'careful', label: 'Eher vorsichtig / diplomatisch.' },
      { value: 'structured', label: 'Strukturiert und gut vorbereitet.' },
    ],
    active: true,
    order: 603,
  },

  // ============ OLD QUESTIONS (keeping for backward compatibility) ============
  {
    key: 'ich_suche',
    question: 'Ich suche:',
    type: 'multiple_choice',
    options: [
      'Kontakte allgemein',
      'Sponsoren',
      'Mitarbeiter / Personal',
      'Finanzierung',
      'Sparringspartner',
      'Beteiligungen',
      'Investitionsmöglichkeiten',
      'Gleichgesinnte Pokerfreunde',
      'Einen Partner fürs Leben',
    ],
    active: true,
    order: 1,
  },
  {
    key: 'einsatz_von_poker_als_lehrmethode',
    question: 'Einsatz von Poker als Lehrmethode für:',
    type: 'multiple_choice',
    options: [
      'Verhandlungsführung',
      'Vertrieb / Sales / Einkauf',
      'Personalwesen / HR',
      'Strengten Women Leadership',
      'Entscheidungskompetenz',
      'Finance',
      'Marketing / PR',
      'Incentives / Events / Kundenbindung',
      'Mindset / Werte + Ziele',
      'Data Science / AI',
      'Cultural Change',
      'Sonstiges',
    ],
    active: true,
    order: 2,
  },
  {
    key: 'parallel_biz_poker',
    question: 'Hier sehe ich Parallelen zwischen meinem Business und dem Pokerspiel:',
    type: 'text',
    options: [''], // Text questions don't need options but the schema requires it
    active: true,
    order: 3,
  },
];

async function seed() {
  try {
    logger.log('Starting question seed...');

    const app = await NestFactory.createApplicationContext(AppModule);
    const personalityService = app.get(PersonalityService);

    let created = 0;
    let skipped = 0;

    for (const questionData of initialQuestions) {
      try {
        await personalityService.createQuestion(questionData);
        logger.log(`✓ Created question: ${questionData.key}`);
        created++;
      } catch (error) {
        if (error.message?.includes('already exists')) {
          logger.log(`⊘ Skipped (already exists): ${questionData.key}`);
          skipped++;
        } else {
          logger.error(`✗ Failed to create question ${questionData.key}:`, error.message);
        }
      }
    }

    logger.log('\n=== Seed Summary ===');
    logger.log(`Created: ${created}`);
    logger.log(`Skipped: ${skipped}`);
    logger.log(`Total questions: ${created + skipped}`);

    await app.close();
    logger.log('Seed completed successfully!');
    process.exit(0);
  } catch (error) {
    logger.error('Seed failed:', error);
    process.exit(1);
  }
}

seed();
